services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    container_name: app-php8
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/.bashrc:/var/www/.bashrc
      - ./config/.bash_history:/var/www/.bash_history
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    working_dir: /var/www/html
    depends_on:
      - db
    user: www-data

  db:
    image: mysql:8.0
    container_name: db-mysql8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app-php8
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data_mysql:
